name: Gatos smoke test
run-name: ${{ github.actor }} testing gatos 🚀

on:   
  pull_request:
    types: [ labeled ]
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry install --no-root
      - run: poetry run python -m unittest gato.tests.gatos.smoke_test
      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: test-gatos
      - name: add success label
        if: ${{ job.status == 'success' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: gato-test-success
      - name: add failure label
        if: ${{ job.status != 'success' }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: gato-test-failure
